/**
 * Auto-generated from the CapitalFlow OpenAPI spec (contract-details endpoints).
 * Each of the 25 contract types has its own request body shape; `other` exists in both
 * the asset and hedge categories with a different shape, which is why the category is
 * now a required part of the URL (`/contract-details/{category}/{type}`).
 */
import type { INodeProperties } from "n8n-workflow";

export const CONTRACT_CATEGORY_OPTIONS = [
	{ name: "Asset", value: "asset" },
	{ name: "Hedge", value: "hedge" },
];

export const ASSET_CONTRACT_TYPE_OPTIONS = [
	{ name: "Building Savings Contract", value: "building_savings_contract" },
	{ name: "Call Money Account", value: "call_money_account" },
	{ name: "Checking Account", value: "checking_account" },
	{ name: "Employer Pension Scheme (bAV)", value: "employer_pension_scheme" },
	{ name: "Investment Account", value: "investment_account" },
	{ name: "Other Asset", value: "other" },
	{ name: "Private Pension", value: "private_pension" },
	{ name: "Property", value: "property" },
	{ name: "Riester Pension", value: "riester" },
	{ name: "Ruerup Pension (Basisrente)", value: "ruerup" },
	{ name: "Savings Book", value: "savings_book" },
];

export const HEDGE_CONTRACT_TYPE_OPTIONS = [
	{ name: "Accident Insurance", value: "accident_insurance" },
	{ name: "Car Insurance", value: "car_insurance" },
	{ name: "Deferred Health Insurance (Anwartschaft)", value: "deferred_health_insurance" },
	{ name: "Dental Supplementary Insurance", value: "dental_supplementary_insurance" },
	{ name: "Household Contents Insurance", value: "household_contents_insurance" },
	{ name: "Income Protection Insurance", value: "income_protection_insurance" },
	{ name: "Legal Protection Insurance", value: "legal_protection_insurance" },
	{ name: "Liability Insurance", value: "liability_insurance" },
	{ name: "Nursing Care Insurance", value: "nursing_care_insurance" },
	{ name: "Optional Health Services", value: "optional_health_services" },
	{ name: "Other Hedge", value: "other" },
	{ name: "Private Health Insurance", value: "private_health_insurance" },
	{ name: "Residential Building Insurance", value: "residential_building_insurance" },
	{ name: "Term Life Insurance", value: "term_life_insurance" },
	{ name: "Travel Health Insurance", value: "travel_health_insurance" },
];

export interface ContractFieldGroup {
	category: "asset" | "hedge";
	type: string;
	paramName: string;
	fields: INodeProperties[];
}

export const CONTRACT_FIELD_GROUPS: ContractFieldGroup[] = [
	{
		category: "asset",
		type: "checking_account",
		paramName: "assetCheckingAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Overdraft Rate",
				name: "overdraft_rate",
				type: "number",
				default: 0,
				description: "Overdraft Interest Rate (%)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "savings_book",
		paramName: "assetSavingsBookFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Interest Rate",
				name: "interest_rate",
				type: "number",
				default: 0,
				description: "Interest Rate (%)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "call_money_account",
		paramName: "assetCallMoneyAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Interest Rate",
				name: "interest_rate",
				type: "number",
				default: 0,
				description: "Interest Rate (%)",
			},
			{
				displayName: "Interest Lock Until",
				name: "interest_lock_until",
				type: "dateTime",
				default: "",
				description: "Fixed Interest Period Until",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "investment_account",
		paramName: "assetInvestmentAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Investment Type",
				name: "investment_type",
				type: "options",
				options: [{ name: "ETF", value: "etf" }, { name: "Fonds", value: "funds" }, { name: "Individual Values", value: "single_stocks" }, { name: "Mix", value: "mixed" }],
				default: "etf",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "building_savings_contract",
		paramName: "assetBuildingSavingsContractFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Building Savings Amount",
				name: "building_savings_amount",
				type: "number",
				default: 0,
				description: "Building Savings Sum (€)",
			},
			{
				displayName: "Current Balance",
				name: "current_balance",
				type: "number",
				default: 0,
				description: "Current Balance (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Savings Interest Rate",
				name: "savings_interest_rate",
				type: "number",
				default: 0,
				description: "Savings Interest Rate (%)",
			},
			{
				displayName: "Loan Interest Rate",
				name: "loan_interest_rate",
				type: "number",
				default: 0,
				description: "Nominal Interest Rate (%)",
			},
			{
				displayName: "Allocation Ready From",
				name: "allocation_ready_from",
				type: "dateTime",
				default: "",
				description: "Eligible for Allocation From",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "property",
		paramName: "assetPropertyFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Address",
				name: "address",
				type: "string",
				default: "",
				description: "Street",
			},
			{
				displayName: "Address Number",
				name: "address_number",
				type: "string",
				default: "",
				description: "House Number",
			},
			{
				displayName: "Zipcode",
				name: "zipcode",
				type: "string",
				default: "",
				description: "Postal Code",
			},
			{
				displayName: "City",
				name: "city",
				type: "string",
				default: "",
			},
			{
				displayName: "Usage Type",
				name: "usage_type",
				type: "options",
				options: [{ name: "Land / Plot", value: "is_land" }, { name: "Owner-Occupied", value: "is_in_selfuse" }, { name: "Partially Rented", value: "is_partly_rented" }, { name: "Rented", value: "is_rented" }],
				default: "is_in_selfuse",
			},
			{
				displayName: "Property Type",
				name: "property_type",
				type: "options",
				options: [{ name: "Condominium", value: "etw" }, { name: "Land / Plot", value: "land" }, { name: "Multi-Family House", value: "mfh" }, { name: "Semi-Detached House", value: "dhh" }, { name: "Single-Family House", value: "efh" }, { name: "Terraced House", value: "rh" }],
				default: "dhh",
			},
			{
				displayName: "Construction Year",
				name: "construction_year",
				type: "number",
				default: 0,
				description: "Year Built",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Living Space (m²)",
			},
			{
				displayName: "Market Value",
				name: "market_value",
				type: "number",
				default: 0,
				description: "Current Market Value (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Rent",
				name: "rent",
				type: "number",
				default: 0,
				description: "Monthly Rental Income (€)",
			},
			{
				displayName: "Has Financing",
				name: "has_financing",
				type: "boolean",
				default: false,
				description: "Whether financing is in place",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Loan Account Number",
				name: "loan_account_number",
				type: "string",
				default: "",
				description: 'Loan account number or credit account IBAN',
			},
			{
				displayName: "Original Loan Amount",
				name: "original_loan_amount",
				type: "number",
				default: 0,
				description: "Original Loan Amount (€)",
			},
			{
				displayName: "Current Outstanding Debt",
				name: "current_outstanding_debt",
				type: "number",
				default: 0,
				description: "Current Remaining Debt (€)",
			},
			{
				displayName: "Debt At Interest Lock End",
				name: "debt_at_interest_lock_end",
				type: "number",
				default: 0,
				description: "Remaining Debt at End of Fixed-Interest Period (€)",
			},
			{
				displayName: "Monthly Loan Rate In Euro",
				name: "monthly_loan_rate_in_euro",
				type: "number",
				default: 0,
				description: "Monthly Loan Installment (€)",
			},
			{
				displayName: "Loan Interest Rate",
				name: "loan_interest_rate",
				type: "number",
				default: 0,
				description: "Nominal Interest Rate (%)",
			},
			{
				displayName: "Effective Interest Rate",
				name: "effective_interest_rate",
				type: "number",
				default: 0,
				description: "Effective Interest Rate (%)",
			},
			{
				displayName: "Bank",
				name: "bank",
				type: "string",
				default: "",
				description: "Bank (Financing)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "private_pension",
		paramName: "assetPrivatePensionFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Classic", value: "classic" }, { name: "Hybrid", value: "hybrid" }, { name: "Index Policy", value: "index" }, { name: "Unit-Linked", value: "fund_linked" }],
				default: "fund_linked",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Assumed Return (%)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamic Increase (%)",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Current Surrender Value (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Guaranteed Pension (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Projected Pension (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Guaranteed Capital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Projected Capital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "Accident Supplement", value: "accident_rider" }, { name: "BUZ", value: "buz" }, { name: "Care Option", value: "care_option" }, { name: "Premium Waiver on Occupational Disability", value: "premium_waiver_bu" }],
				default: [],
				description: "Additional Modules",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "Occupational Disability Monthly Pension (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Accident Supplement Sum (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Death Capital", value: "death_capital" }, { name: "Pension Guarantee Period", value: "pension_guarantee_period" }, { name: "Premium Refund", value: "premium_refund" }, { name: "Survivor Pension", value: "survivor_pension" }],
				default: [],
				description: "Death/Survivor Protection",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Pension Guarantee Period (Years)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Death Benefit Capital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "ruerup",
		paramName: "assetRuerupFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Classic", value: "classic" }, { name: "Hybrid", value: "hybrid" }, { name: "Index Policy", value: "index" }, { name: "Unit-Linked", value: "fund_linked" }],
				default: "fund_linked",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Assumed Return (%)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamic Increase (%)",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Current Surrender Value (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Guaranteed Pension (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Projected Pension (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Guaranteed Capital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Projected Capital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "Accident Supplement", value: "accident_rider" }, { name: "BUZ", value: "buz" }, { name: "Care Option", value: "care_option" }, { name: "Premium Waiver on Occupational Disability", value: "premium_waiver_bu" }],
				default: [],
				description: "Additional Modules",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "Occupational Disability Monthly Pension (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Accident Supplement Sum (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Death Capital", value: "death_capital" }, { name: "Pension Guarantee Period", value: "pension_guarantee_period" }, { name: "Premium Refund", value: "premium_refund" }, { name: "Survivor Pension", value: "survivor_pension" }],
				default: [],
				description: "Death/Survivor Protection",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Pension Guarantee Period (Years)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Death Benefit Capital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "riester",
		paramName: "assetRiesterFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Bank Savings Plan", value: "bank_savings" }, { name: "Classic", value: "classic" }, { name: "Home Riester", value: "wohn_riester" }, { name: "Unit-Linked", value: "fund_linked" }],
				default: "bank_savings",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Assumed Return (%)",
			},
			{
				displayName: "Eligible Children",
				name: "eligible_children",
				type: "number",
				default: 0,
				description: "Children Eligible for Allowance",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Current Surrender Value (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Guaranteed Pension (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Projected Pension (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Guaranteed Capital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Projected Capital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Survivor Protection Simple",
				name: "survivor_protection_simple",
				type: "boolean",
				default: false,
				description: "Whether survivor protection is included",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "employer_pension_scheme",
		paramName: "assetEmployerPensionSchemeFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Pension Scheme Type",
				name: "pension_scheme_type",
				type: "options",
				options: [{ name: "Direct Commitment", value: "direct_commitment" }, { name: "Direct Insurance", value: "direct_insurance" }, { name: "Pension Fund", value: "pension_fund" }, { name: "Pension Trust", value: "pension_trust" }, { name: "Support Fund", value: "support_fund" }],
				default: "direct_insurance",
				description: "Implementation Channel",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Classic", value: "classic" }, { name: "Hybrid", value: "hybrid" }, { name: "Unit-Linked", value: "fund_linked" }],
				default: "fund_linked",
			},
			{
				displayName: "Funding Type",
				name: "funding_type",
				type: "options",
				options: [{ name: "Employer-Financed", value: "employer_funded" }, { name: "Mixed Financing", value: "mixed" }, { name: "Salary Conversion (Employee-Financed)", value: "salary_conversion" }],
				default: "employer_funded",
				description: "Financing Type",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Assumed Return (%)",
			},
			{
				displayName: "Service Entry Date",
				name: "service_entry_date",
				type: "dateTime",
				default: "",
				description: "Date of Service Entry",
			},
			{
				displayName: "Vesting Date",
				name: "vesting_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Contribution Distribution",
				name: "contribution_distribution",
				type: "options",
				options: [{ name: "Employer Contribution", value: "employer_contribution" }, { name: "Own Contribution", value: "personal_contribution" }, { name: "Total Contribution", value: "total_contribution" }],
				default: "employer_contribution",
				description: "Premium Split",
			},
			{
				displayName: "Employer Contribution Type",
				name: "employer_contribution_type",
				type: "options",
				options: [{ name: "Value In %", value: "percent" }, { name: "Value In €", value: "total" }],
				default: "percent",
				description: "Type of Employer Subsidy",
			},
			{
				displayName: "Employer Contribution Value",
				name: "employer_contribution_value",
				type: "number",
				default: 0,
				description: "Employer Subsidy",
			},
			{
				displayName: "Current Contract Value",
				name: "current_contract_value",
				type: "number",
				default: 0,
				description: "Current Contract Value (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Values as of",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Guaranteed Pension (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Projected Pension (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Guaranteed Capital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Projected Capital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "Accident Supplement", value: "accident_rider" }, { name: "BUZ", value: "buz" }, { name: "Care Option", value: "care_option" }, { name: "Premium Waiver on Occupational Disability", value: "premium_waiver_bu" }],
				default: [],
				description: "Additional Modules",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "Occupational Disability Monthly Pension (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Accident Supplement Sum (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Death Capital", value: "death_capital" }, { name: "Pension Guarantee Period", value: "pension_guarantee_period" }, { name: "Premium Refund", value: "premium_refund" }, { name: "Survivor Pension", value: "survivor_pension" }],
				default: [],
				description: "Death/Survivor Protection",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Pension Guarantee Period (Years)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Death Benefit Capital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "other",
		paramName: "assetOtherFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value",
			},
			{
				displayName: "Duration",
				name: "duration",
				type: "options",
				options: [{ name: "Long-Term", value: "long" }, { name: "Medium-Term", value: "middle" }, { name: "Short-Term", value: "short" }],
				default: "middle",
				description: 'Duration bucket. For typed asset endpoints this is derived server-side from the contract type — only `/asset/other` accepts a client-supplied value.',
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "liability_insurance",
		paramName: "hedgeLiabilityInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Insured Sum (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Deductible (€)",
			},
			{
				displayName: "Family Status",
				name: "family_status",
				type: "options",
				options: [{ name: "Couple", value: "couple" }, { name: "Family", value: "family" }, { name: "Single", value: "single" }],
				default: "family",
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Children Not Liable for Damages", value: "incapable_children" }, { name: "Courtesy Damages", value: "courtesy_damages" }, { name: "Default on Claims", value: "default_failure" }, { name: "Key Loss", value: "key_loss" }, { name: "Water Damage", value: "water_damage" }],
				default: [],
				description: "Included Modules",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "car_insurance",
		paramName: "hedgeCarInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "License Plate",
				name: "license_plate",
				type: "string",
				default: "",
			},
			{
				displayName: "Hsn",
				name: "hsn",
				type: "string",
				default: "",
			},
			{
				displayName: "Tsn",
				name: "tsn",
				type: "string",
				default: "",
			},
			{
				displayName: "Initial Registration Date",
				name: "initial_registration_date",
				type: "dateTime",
				default: "",
				description: "First Registration",
			},
			{
				displayName: "Coverage Scope",
				name: "coverage_scope",
				type: "options",
				options: [{ name: "Comprehensive", value: "full" }, { name: "Liability", value: "liability" }, { name: "Liability + Partial Comprehensive", value: "liability_partial" }],
				default: "liability",
				description: "Coverage Type",
			},
			{
				displayName: "No Claims Class Liability",
				name: "no_claims_class_liability",
				type: "string",
				default: "",
				description: "No-Claims Class Liability",
			},
			{
				displayName: "No Claims Class Full",
				name: "no_claims_class_full",
				type: "string",
				default: "",
				description: "No-Claims Class Comprehensive",
			},
			{
				displayName: "Partial Deductible",
				name: "partial_deductible",
				type: "number",
				default: 0,
				description: "Deductible Partial Coverage (€)",
			},
			{
				displayName: "Full Deductible",
				name: "full_deductible",
				type: "number",
				default: 0,
				description: "Deductible Comprehensive Coverage (€)",
			},
			{
				displayName: "Annual Mileage",
				name: "annual_mileage",
				type: "number",
				default: 0,
				description: "Annual Mileage (km)",
			},
			{
				displayName: "Driver Group",
				name: "driver_group",
				type: "options",
				options: [{ name: "Family", value: "family" }, { name: "Open", value: "open" }, { name: "Policyholder + Partner", value: "vn_partner" }, { name: "Policyholder Only", value: "vn_only" }],
				default: "family",
				description: "User Group",
			},
			{
				displayName: "Add Ons",
				name: "add_ons",
				type: "multiOptions",
				options: [{ name: "Driver Protection", value: "driver_protection" }, { name: "GAP", value: "gap" }, { name: "No-Claims Bonus Protection", value: "discount_protection" }, { name: "Roadside Assistance", value: "roadside" }, { name: "Workshop Commitment", value: "workshop_binding" }],
				default: [],
				description: "Additional Modules",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "household_contents_insurance",
		paramName: "hedgeHouseholdContentsInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Insured Sum (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Deductible (€)",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Living Space (m²)",
			},
			{
				displayName: "Risk Street",
				name: "risk_street",
				type: "string",
				default: "",
				description: "Risk Location: Street",
			},
			{
				displayName: "Risk Street Number",
				name: "risk_street_number",
				type: "string",
				default: "",
				description: "Risk Location: House Number",
			},
			{
				displayName: "Risk Zipcode",
				name: "risk_zipcode",
				type: "string",
				default: "",
				description: "Risk Location: Postal Code",
			},
			{
				displayName: "Risk City",
				name: "risk_city",
				type: "string",
				default: "",
				description: "Risk Location: City",
			},
			{
				displayName: "Burglary Alarm",
				name: "burglary_alarm",
				type: "boolean",
				default: false,
				description: "Whether a burglar alarm system is present",
			},
			{
				displayName: "Elemental Coverage",
				name: "elemental_coverage",
				type: "boolean",
				default: false,
				description: "Whether natural hazard damage is included",
			},
			{
				displayName: "Glass Coverage",
				name: "glass_coverage",
				type: "boolean",
				default: false,
				description: "Whether glass breakage is included",
			},
			{
				displayName: "Bicycle Coverage Sum",
				name: "bicycle_coverage_sum",
				type: "number",
				default: 0,
				description: "Bicycle Clause Amount (€)",
			},
			{
				displayName: "Valuables Sum",
				name: "valuables_sum",
				type: "number",
				default: 0,
				description: "Valuables Sum (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "legal_protection_insurance",
		paramName: "hedgeLegalProtectionInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Coverage Amount (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Deductible (€)",
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Commercial", value: "business" }, { name: "Homeowner", value: "owner" }, { name: "Occupation", value: "job" }, { name: "Private", value: "private" }, { name: "Rental Property", value: "rental_property" }, { name: "Tenant", value: "tenant" }, { name: "Traffic", value: "traffic" }],
				default: [],
				description: "Included Modules",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "residential_building_insurance",
		paramName: "hedgeResidentialBuildingInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Insured Sum / 1914 Value (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Deductible (€)",
			},
			{
				displayName: "Risk Street",
				name: "risk_street",
				type: "string",
				default: "",
				description: "Risk Location: Street",
			},
			{
				displayName: "Risk Street Number",
				name: "risk_street_number",
				type: "string",
				default: "",
				description: "Risk Location: House Number",
			},
			{
				displayName: "Risk Zipcode",
				name: "risk_zipcode",
				type: "string",
				default: "",
				description: "Risk Location: Postal Code",
			},
			{
				displayName: "Risk City",
				name: "risk_city",
				type: "string",
				default: "",
				description: "Risk Location: City",
			},
			{
				displayName: "Building Type",
				name: "building_type",
				type: "options",
				options: [{ name: "Multi-Family House", value: "mfh" }, { name: "Semi-Detached House", value: "dhh" }, { name: "Single-Family House", value: "efh" }, { name: "Terraced House", value: "rh" }],
				default: "dhh",
			},
			{
				displayName: "Construction Year",
				name: "construction_year",
				type: "number",
				default: 0,
				description: "Year Built",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Living Space (m²)",
			},
			{
				displayName: "Construction Class",
				name: "construction_class",
				type: "options",
				options: [{ name: "Prefabricated House", value: "prefab" }, { name: "Solid Construction", value: "solid" }, { name: "Wood", value: "wood" }],
				default: "prefab",
				description: "Construction Type Class",
			},
			{
				displayName: "Roof Type",
				name: "roof_type",
				type: "options",
				options: [{ name: "Hard", value: "hard" }, { name: "Soft", value: "soft" }],
				default: "hard",
				description: "Roof Covering",
			},
			{
				displayName: "Hazards",
				name: "hazards",
				type: "multiOptions",
				options: [{ name: "Fire", value: "fire" }, { name: "Natural Hazards", value: "elemental" }, { name: "Storm + Hail", value: "storm_hail" }, { name: "Unnamed Hazards", value: "unnamed" }, { name: "Water Damage (Pipes)", value: "water" }],
				default: [],
				description: "Included Hazards",
			},
			{
				displayName: "Photovoltaic Coverage",
				name: "photovoltaic_coverage",
				type: "boolean",
				default: false,
				description: "Whether photovoltaic systems are included",
			},
			{
				displayName: "Gross Negligence",
				name: "gross_negligence",
				type: "boolean",
				default: false,
				description: "Whether gross negligence is included",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "accident_insurance",
		paramName: "hedgeAccidentInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Base Sum for Disability (€)",
			},
			{
				displayName: "Progression Rate",
				name: "progression_rate",
				type: "options",
				options: [{ name: "100 %", value: "100" }, { name: "1000 %", value: "1000" }, { name: "225 %", value: "225" }, { name: "350 %", value: "350" }, { name: "500 %", value: "500" }],
				default: "100",
				description: "Progression",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamic Increase (%)",
			},
			{
				displayName: "Accident Pension From Invalidity",
				name: "accident_pension_from_invalidity",
				type: "number",
				default: 0,
				description: "Accident Pension From Disability (%)",
			},
			{
				displayName: "Monthly Accident Pension",
				name: "monthly_accident_pension",
				type: "number",
				default: 0,
				description: "Monthly Accident Pension (€)",
			},
			{
				displayName: "Hospital Daily Allowance",
				name: "hospital_daily_allowance",
				type: "number",
				default: 0,
				description: "Hospital Daily Allowance (€)",
			},
			{
				displayName: "Accident Death Benefit",
				name: "accident_death_benefit",
				type: "number",
				default: 0,
				description: "Death Benefit Sum (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "term_life_insurance",
		paramName: "hedgeTermLifeInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Insured Sum (€)",
			},
			{
				displayName: "Sum Progression",
				name: "sum_progression",
				type: "options",
				options: [{ name: "Annuity Declining", value: "annuity_falling" }, { name: "Constant", value: "constant" }, { name: "Linear Declining", value: "linear_falling" }],
				default: "annuity_falling",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamic Increase (%)",
			},
			{
				displayName: "Subsequent Insurance Guarantee",
				name: "subsequent_insurance_guarantee",
				type: "boolean",
				default: false,
				description: "Whether the guaranteed insurability option is included",
			},
			{
				displayName: "Smoker Status",
				name: "smoker_status",
				type: "options",
				options: [{ name: "Non-Smoker", value: "non_smoker" }, { name: "Smoker", value: "smoker" }],
				default: "non_smoker",
				description: "Smoker Status at Application",
			},
			{
				displayName: "Purpose",
				name: "purpose",
				type: "options",
				options: [{ name: "Business Partner", value: "business_partner" }, { name: "Family", value: "family" }, { name: "Financing", value: "financing" }],
				default: "family",
				description: "Purpose of Use",
			},
			{
				displayName: "Cross Insurance",
				name: "cross_insurance",
				type: "boolean",
				default: false,
				description: "Whether cross insurance applies",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "income_protection_insurance",
		paramName: "hedgeIncomeProtectionInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Insured Monthly Pension (€)",
			},
			{
				displayName: "Benefit Until Age",
				name: "benefit_until_age",
				type: "number",
				default: 0,
				description: "Benefit Duration Until Age",
			},
			{
				displayName: "Occupation At Application",
				name: "occupation_at_application",
				type: "string",
				default: "",
			},
			{
				displayName: "Contribution Dynamic",
				name: "contribution_dynamic",
				type: "number",
				default: 0,
				description: "Premium Dynamic (%)",
			},
			{
				displayName: "Benefit Dynamic",
				name: "benefit_dynamic",
				type: "number",
				default: 0,
				description: "Benefit Dynamic (%)",
			},
			{
				displayName: "Risk Surcharges Exclusions",
				name: "risk_surcharges_exclusions",
				type: "string",
				default: "",
				description: "Risk Surcharges / Exclusions",
			},
			{
				displayName: "Subsequent Insurance Guarantee",
				name: "subsequent_insurance_guarantee",
				type: "boolean",
				default: false,
				description: "Whether the guaranteed insurability option is included",
			},
			{
				displayName: "BU Riders",
				name: "bu_riders",
				type: "multiOptions",
				options: [{ name: "Care Option", value: "care_option" }, { name: "Incapacity-to-Work Clause", value: "au_clause" }, { name: "Premium Waiver", value: "premium_waiver" }, { name: "Severe Illnesses", value: "dread_disease" }],
				default: [],
				description: "Included Add-On Modules",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "optional_health_services",
		paramName: "hedgeOptionalHealthServicesFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Accommodation",
				name: "accommodation",
				type: "options",
				options: [{ name: "Double Room", value: "two_bed" }, { name: "Single Room", value: "single_bed" }],
				default: "single_bed",
			},
			{
				displayName: "Chief Physician Treatment",
				name: "chief_physician_treatment",
				type: "boolean",
				default: false,
				description: "Whether chief physician treatment is included",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "With", value: "with" }, { name: "Without", value: "without" }],
				default: "with",
				description: "Age-Related Reserves",
			},
			{
				displayName: "Waiting Period Expired",
				name: "waiting_period_expired",
				type: "boolean",
				default: false,
				description: "Whether the waiting period has expired",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "deferred_health_insurance",
		paramName: "hedgeDeferredHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Anwartschaft Type",
				name: "anwartschaft_type",
				type: "options",
				options: [{ name: "Large Deferred Entitlement", value: "large" }, { name: "Small Deferred Entitlement", value: "small" }],
				default: "large",
				description: "Type of Deferred Entitlement",
			},
			{
				displayName: "Target Tariff",
				name: "target_tariff",
				type: "string",
				default: "",
				description: "Target Tariff (Private Health Insurance/Supplementary)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "dental_supplementary_insurance",
		paramName: "hedgeDentalSupplementaryInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Dental Replacement Reimbursement",
				name: "dental_replacement_reimbursement",
				type: "number",
				default: 0,
				description: "Reimbursement for Dentures (%)",
			},
			{
				displayName: "Dental Treatment Reimbursement",
				name: "dental_treatment_reimbursement",
				type: "number",
				default: 0,
				description: "Reimbursement for Dental Treatment (%)",
			},
			{
				displayName: "Prophylaxis Reimbursement",
				name: "prophylaxis_reimbursement",
				type: "number",
				default: 0,
				description: "Reimbursement for Prophylaxis (%)",
			},
			{
				displayName: "Annual Max Staging",
				name: "annual_max_staging",
				type: "string",
				default: "",
				description: "Annual Maximum Rate / Tiering",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "With", value: "with" }, { name: "Without", value: "without" }],
				default: "with",
				description: "Age-Related Reserves",
			},
			{
				displayName: "Waiting Period Expired",
				name: "waiting_period_expired",
				type: "boolean",
				default: false,
				description: "Whether the waiting period has expired",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "travel_health_insurance",
		paramName: "hedgeTravelHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Persons Travel",
				name: "insured_persons_travel",
				type: "options",
				options: [{ name: "Couple", value: "couple" }, { name: "Family", value: "family" }, { name: "Individual", value: "single" }],
				default: "single",
				description: "Insured Persons",
			},
			{
				displayName: "Max Travel Duration Days",
				name: "max_travel_duration_days",
				type: "number",
				default: 0,
				description: 'Maximum trip duration (days)',
			},
			{
				displayName: "Repatriation Included",
				name: "repatriation_included",
				type: "boolean",
				default: false,
				description: "Whether return transport is included",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "private_health_insurance",
		paramName: "hedgePrivateHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Status",
				name: "insured_status",
				type: "options",
				options: [{ name: "Child", value: "child" }, { name: "Civil Servant", value: "civil_servant" }, { name: "Employee Above Income Threshold (JAEG)", value: "employee_above_jaeg" }, { name: "Self-Employed", value: "self_employed" }, { name: "Student", value: "student" }],
				default: "employee_above_jaeg",
			},
			{
				displayName: "Aid Rate",
				name: "aid_rate",
				type: "number",
				default: 0,
				description: "Allowance Rate (for Civil Servants) (%)",
			},
			{
				displayName: "Annual Deductible",
				name: "annual_deductible",
				type: "number",
				default: 0,
				description: 'Annual deductible (€)',
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Daily Care Allowance", value: "care_allowance" }, { name: "Daily Sickness Allowance", value: "daily_allowance" }, { name: "Dental", value: "dental" }, { name: "Inpatient", value: "inpatient" }, { name: "Outpatient", value: "outpatient" }],
				default: [],
				description: "Included Modules",
			},
			{
				displayName: "Inpatient Benefit",
				name: "inpatient_benefit",
				type: "options",
				options: [{ name: "Double Room", value: "two_bed" }, { name: "Multi-Bed Room", value: "multi_bed" }, { name: "Single Room + Chief Physician", value: "single_bed_chief" }],
				default: "single_bed_chief",
			},
			{
				displayName: "Dental Benefit",
				name: "dental_benefit",
				type: "number",
				default: 0,
				description: "Dental Benefit (%)",
			},
			{
				displayName: "Contribution Relief Tariff",
				name: "contribution_relief_tariff",
				type: "boolean",
				default: false,
				description: "Whether the premium relief tariff is included",
			},
			{
				displayName: "Relief From Age",
				name: "relief_from_age",
				type: "number",
				default: 0,
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "nursing_care_insurance",
		paramName: "hedgeNursingCareInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
			},
			{
				displayName: "Care Insurance Type",
				name: "care_insurance_type",
				type: "options",
				options: [{ name: "Care Costs", value: "costs" }, { name: "Care Pension", value: "pension" }, { name: "Daily Care Allowance", value: "daily_allowance" }],
				default: "costs",
				description: "Type of Nursing Care Insurance",
			},
			{
				displayName: "Care Benefit Pg2",
				name: "care_benefit_pg2",
				type: "number",
				default: 0,
				description: "Benefit Care Level 2 (€)",
			},
			{
				displayName: "Care Benefit Pg3",
				name: "care_benefit_pg3",
				type: "number",
				default: 0,
				description: "Benefit Care Level 3 (€)",
			},
			{
				displayName: "Care Benefit Pg4",
				name: "care_benefit_pg4",
				type: "number",
				default: 0,
				description: "Benefit Care Level 4 (€)",
			},
			{
				displayName: "Care Benefit Pg5",
				name: "care_benefit_pg5",
				type: "number",
				default: 0,
				description: "Benefit Care Level 5 (€)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamic Increase (%)",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "With", value: "with" }, { name: "Without", value: "without" }],
				default: "with",
				description: "Age-Related Reserves",
			},
			{
				displayName: "Premium Waiver On Benefit",
				name: "premium_waiver_on_benefit",
				type: "boolean",
				default: false,
				description: "Whether premium waiver applies in the event of a claim",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "other",
		paramName: "hedgeOtherFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Contract Partner (Company)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Current Value in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "Bi-Monthly", value: "bi_monthly" }, { name: "Bi-Weekly", value: "bi_weekly" }, { name: "Half-Yearly", value: "half_yearly" }, { name: "Monthly", value: "monthly" }, { name: "Quarterly", value: "quarterly" }, { name: "Weekly", value: "weekly" }, { name: "Yearly", value: "yearly" }],
				default: "monthly",
				description: "Payment Interval of the Premium",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Short Description of the Contract",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
];
