/**
 * Auto-generated from the CapitalFlow OpenAPI spec (contract-details endpoints).
 * Each of the 25 contract types has its own request body shape; `other` exists in both
 * the asset and hedge categories with a different shape, which is why the category is
 * now a required part of the URL (`/contract-details/{category}/{type}`).
 */
import type { INodeProperties } from "n8n-workflow";

export const CONTRACT_CATEGORY_OPTIONS = [
	{ name: "Asset (Vermögenswert)", value: "asset" },
	{ name: "Hedge (Absicherung)", value: "hedge" },
];

export const ASSET_CONTRACT_TYPE_OPTIONS = [
	{ name: "Building Savings Contract", value: "building_savings_contract" },
	{ name: "Call Money Account", value: "call_money_account" },
	{ name: "Checking Account", value: "checking_account" },
	{ name: "Employer Pension Scheme (bAV)", value: "employer_pension_scheme" },
	{ name: "Investment Account", value: "investment_account" },
	{ name: "Other Asset", value: "other" },
	{ name: "Private Pension", value: "private_pension" },
	{ name: "Property", value: "property" },
	{ name: "Riester Pension", value: "riester" },
	{ name: "Ruerup Pension (Basisrente)", value: "ruerup" },
	{ name: "Savings Book", value: "savings_book" },
];

export const HEDGE_CONTRACT_TYPE_OPTIONS = [
	{ name: "Accident Insurance", value: "accident_insurance" },
	{ name: "Car Insurance", value: "car_insurance" },
	{ name: "Deferred Health Insurance (Anwartschaft)", value: "deferred_health_insurance" },
	{ name: "Dental Supplementary Insurance", value: "dental_supplementary_insurance" },
	{ name: "Household Contents Insurance", value: "household_contents_insurance" },
	{ name: "Income Protection Insurance", value: "income_protection_insurance" },
	{ name: "Legal Protection Insurance", value: "legal_protection_insurance" },
	{ name: "Liability Insurance", value: "liability_insurance" },
	{ name: "Nursing Care Insurance", value: "nursing_care_insurance" },
	{ name: "Optional Health Services", value: "optional_health_services" },
	{ name: "Other Hedge", value: "other" },
	{ name: "Private Health Insurance", value: "private_health_insurance" },
	{ name: "Residential Building Insurance", value: "residential_building_insurance" },
	{ name: "Term Life Insurance", value: "term_life_insurance" },
	{ name: "Travel Health Insurance", value: "travel_health_insurance" },
];

export interface ContractFieldGroup {
	category: "asset" | "hedge";
	type: string;
	paramName: string;
	fields: INodeProperties[];
}

export const CONTRACT_FIELD_GROUPS: ContractFieldGroup[] = [
	{
		category: "asset",
		type: "checking_account",
		paramName: "assetCheckingAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
				description: "Kontonummer",
			},
			{
				displayName: "Overdraft Rate",
				name: "overdraft_rate",
				type: "number",
				default: 0,
				description: "Dispozins (%)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "savings_book",
		paramName: "assetSavingsBookFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
				description: "Kontonummer",
			},
			{
				displayName: "Interest Rate",
				name: "interest_rate",
				type: "number",
				default: 0,
				description: "Zins (%)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "call_money_account",
		paramName: "assetCallMoneyAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
				description: "Kontonummer",
			},
			{
				displayName: "Interest Rate",
				name: "interest_rate",
				type: "number",
				default: 0,
				description: "Zins (%)",
			},
			{
				displayName: "Interest Lock Until",
				name: "interest_lock_until",
				type: "dateTime",
				default: "",
				description: "Zinsbindung bis",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "investment_account",
		paramName: "assetInvestmentAccountFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Account Number",
				name: "account_number",
				type: "string",
				default: "",
				description: "Kontonummer",
			},
			{
				displayName: "Investment Type",
				name: "investment_type",
				type: "options",
				options: [{ name: "ETF", value: "etf" }, { name: "Einzelwerte", value: "single_stocks" }, { name: "Fonds", value: "funds" }, { name: "Mischung", value: "mixed" }],
				default: "etf",
				description: "Anlageart",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "building_savings_contract",
		paramName: "assetBuildingSavingsContractFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Building Savings Amount",
				name: "building_savings_amount",
				type: "number",
				default: 0,
				description: "Bausparsumme (€)",
			},
			{
				displayName: "Current Balance",
				name: "current_balance",
				type: "number",
				default: 0,
				description: "Aktuelles Guthaben (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Savings Interest Rate",
				name: "savings_interest_rate",
				type: "number",
				default: 0,
				description: "Sparzins (%)",
			},
			{
				displayName: "Loan Interest Rate",
				name: "loan_interest_rate",
				type: "number",
				default: 0,
				description: "Sollzins (%)",
			},
			{
				displayName: "Allocation Ready From",
				name: "allocation_ready_from",
				type: "dateTime",
				default: "",
				description: "Zuteilungsreif ab",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "property",
		paramName: "assetPropertyFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Address",
				name: "address",
				type: "string",
				default: "",
				description: "Straße",
			},
			{
				displayName: "Address Number",
				name: "address_number",
				type: "string",
				default: "",
				description: "Hausnummer",
			},
			{
				displayName: "Zipcode",
				name: "zipcode",
				type: "string",
				default: "",
				description: "PLZ",
			},
			{
				displayName: "City",
				name: "city",
				type: "string",
				default: "",
				description: "Stadt",
			},
			{
				displayName: "Usage Type",
				name: "usage_type",
				type: "options",
				options: [{ name: "Eigengenutzt", value: "is_in_selfuse" }, { name: "Grundstück", value: "is_land" }, { name: "Teilvermietet", value: "is_partly_rented" }, { name: "Vermietet", value: "is_rented" }],
				default: "is_in_selfuse",
				description: "Nutzungsart",
			},
			{
				displayName: "Property Type",
				name: "property_type",
				type: "options",
				options: [{ name: "Doppelhaushälfte", value: "dhh" }, { name: "Eigentumswohnung", value: "etw" }, { name: "Einfamilienhaus", value: "efh" }, { name: "Grundstück", value: "land" }, { name: "Mehrfamilienhaus", value: "mfh" }, { name: "Reihenhaus", value: "rh" }],
				default: "dhh",
				description: "Immobilienart",
			},
			{
				displayName: "Construction Year",
				name: "construction_year",
				type: "number",
				default: 0,
				description: "Baujahr",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Wohnfläche (m²)",
			},
			{
				displayName: "Market Value",
				name: "market_value",
				type: "number",
				default: 0,
				description: "Aktueller Verkehrswert (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Rent",
				name: "rent",
				type: "number",
				default: 0,
				description: "Monatliche Mieteinnahmen (€)",
			},
			{
				displayName: "Has Financing",
				name: "has_financing",
				type: "boolean",
				default: false,
				description: "Whether finanzierung vorhanden",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Loan Account Number",
				name: "loan_account_number",
				type: "string",
				default: "",
				description: 'Darlehenskonto-Nr. / Kreditkonto-IBAN.',
			},
			{
				displayName: "Original Loan Amount",
				name: "original_loan_amount",
				type: "number",
				default: 0,
				description: "Ursprüngliche Darlehenssumme (€)",
			},
			{
				displayName: "Current Outstanding Debt",
				name: "current_outstanding_debt",
				type: "number",
				default: 0,
				description: "Aktuelle Restschuld (€)",
			},
			{
				displayName: "Debt At Interest Lock End",
				name: "debt_at_interest_lock_end",
				type: "number",
				default: 0,
				description: "Restschuld bei Zinsbindungsende (€)",
			},
			{
				displayName: "Monthly Loan Rate In Euro",
				name: "monthly_loan_rate_in_euro",
				type: "number",
				default: 0,
				description: "Monatliche Darlehensrate (€)",
			},
			{
				displayName: "Loan Interest Rate",
				name: "loan_interest_rate",
				type: "number",
				default: 0,
				description: "Sollzins (%)",
			},
			{
				displayName: "Effective Interest Rate",
				name: "effective_interest_rate",
				type: "number",
				default: 0,
				description: "Effektivzins (%)",
			},
			{
				displayName: "Bank",
				name: "bank",
				type: "string",
				default: "",
				description: "Bank (Finanzierung)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "private_pension",
		paramName: "assetPrivatePensionFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Fondsgebunden", value: "fund_linked" }, { name: "Hybrid", value: "hybrid" }, { name: "Indexpolice", value: "index" }, { name: "Klassisch", value: "classic" }],
				default: "fund_linked",
				description: "Tarifart",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Angenommene Rendite (%)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamik (%)",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Aktueller Rückkaufswert (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Garantierte Rente (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Prognostizierte Rente (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Garantiertes Kapital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Prognostiziertes Kapital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "BUZ", value: "buz" }, { name: "Beitragsbefreiung Bei BU", value: "premium_waiver_bu" }, { name: "Pflegeoption", value: "care_option" }, { name: "Unfall-Zusatz", value: "accident_rider" }],
				default: [],
				description: "Zusatzbausteine",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "BUZ-Monatsrente (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Unfall-Zusatz Summe (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Beitragsrückgewähr", value: "premium_refund" }, { name: "Hinterbliebenenrente", value: "survivor_pension" }, { name: "Rentengarantiezeit", value: "pension_guarantee_period" }, { name: "Todesfallkapital", value: "death_capital" }],
				default: [],
				description: "Todesfall-/Hinterbliebenenschutz",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Rentengarantiezeit (Jahre)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Todesfallkapital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "ruerup",
		paramName: "assetRuerupFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Fondsgebunden", value: "fund_linked" }, { name: "Hybrid", value: "hybrid" }, { name: "Indexpolice", value: "index" }, { name: "Klassisch", value: "classic" }],
				default: "fund_linked",
				description: "Tarifart",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Angenommene Rendite (%)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamik (%)",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Aktueller Rückkaufswert (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Garantierte Rente (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Prognostizierte Rente (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Garantiertes Kapital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Prognostiziertes Kapital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "BUZ", value: "buz" }, { name: "Beitragsbefreiung Bei BU", value: "premium_waiver_bu" }, { name: "Pflegeoption", value: "care_option" }, { name: "Unfall-Zusatz", value: "accident_rider" }],
				default: [],
				description: "Zusatzbausteine",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "BUZ-Monatsrente (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Unfall-Zusatz Summe (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Beitragsrückgewähr", value: "premium_refund" }, { name: "Hinterbliebenenrente", value: "survivor_pension" }, { name: "Rentengarantiezeit", value: "pension_guarantee_period" }, { name: "Todesfallkapital", value: "death_capital" }],
				default: [],
				description: "Todesfall-/Hinterbliebenenschutz",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Rentengarantiezeit (Jahre)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Todesfallkapital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "riester",
		paramName: "assetRiesterFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Banksparplan", value: "bank_savings" }, { name: "Fondsgebunden", value: "fund_linked" }, { name: "Klassisch", value: "classic" }, { name: "Wohn-Riester", value: "wohn_riester" }],
				default: "bank_savings",
				description: "Tarifart",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Angenommene Rendite (%)",
			},
			{
				displayName: "Eligible Children",
				name: "eligible_children",
				type: "number",
				default: 0,
				description: "Zulagenberechtigte Kinder",
			},
			{
				displayName: "Surrender Value",
				name: "surrender_value",
				type: "number",
				default: 0,
				description: "Aktueller Rückkaufswert (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Garantierte Rente (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Prognostizierte Rente (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Garantiertes Kapital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Prognostiziertes Kapital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Survivor Protection Simple",
				name: "survivor_protection_simple",
				type: "boolean",
				default: false,
				description: "Whether hinterbliebenenschutz",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "employer_pension_scheme",
		paramName: "assetEmployerPensionSchemeFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Pension Scheme Type",
				name: "pension_scheme_type",
				type: "options",
				options: [{ name: "Direktversicherung", value: "direct_insurance" }, { name: "Direktzusage", value: "direct_commitment" }, { name: "Pensionsfonds", value: "pension_trust" }, { name: "Pensionskasse", value: "pension_fund" }, { name: "Unterstützungskasse", value: "support_fund" }],
				default: "direct_insurance",
				description: "Durchführungsweg",
			},
			{
				displayName: "Tariff Type",
				name: "tariff_type",
				type: "options",
				options: [{ name: "Fondsgebunden", value: "fund_linked" }, { name: "Hybrid", value: "hybrid" }, { name: "Klassisch", value: "classic" }],
				default: "fund_linked",
				description: "Tarifart",
			},
			{
				displayName: "Funding Type",
				name: "funding_type",
				type: "options",
				options: [{ name: "AG-Finanziert", value: "employer_funded" }, { name: "Entgeltumwandlung (AN-Finanziert)", value: "salary_conversion" }, { name: "Mischfinanzierung", value: "mixed" }],
				default: "employer_funded",
				description: "Finanzierungsart",
			},
			{
				displayName: "Return Rate",
				name: "return_rate",
				type: "number",
				default: 0,
				description: "Angenommene Rendite (%)",
			},
			{
				displayName: "Service Entry Date",
				name: "service_entry_date",
				type: "dateTime",
				default: "",
				description: "Diensteintrittsdatum",
			},
			{
				displayName: "Vesting Date",
				name: "vesting_date",
				type: "dateTime",
				default: "",
				description: "Unverfallbarkeitsdatum",
			},
			{
				displayName: "Contribution Distribution",
				name: "contribution_distribution",
				type: "options",
				options: [{ name: "AG-Beitrag", value: "employer_contribution" }, { name: "Eigenbeitrag", value: "personal_contribution" }, { name: "Gesamtbeitrag", value: "total_contribution" }],
				default: "employer_contribution",
				description: "Beitragsaufteilung",
			},
			{
				displayName: "Employer Contribution Type",
				name: "employer_contribution_type",
				type: "options",
				options: [{ name: "Wert In %", value: "percent" }, { name: "Wert In €", value: "total" }],
				default: "percent",
				description: "Art des Arbeitgeberzuschusses",
			},
			{
				displayName: "Employer Contribution Value",
				name: "employer_contribution_value",
				type: "number",
				default: 0,
				description: "Arbeitgeberzuschuss",
			},
			{
				displayName: "Current Contract Value",
				name: "current_contract_value",
				type: "number",
				default: 0,
				description: "Aktueller Vertragswert (€)",
			},
			{
				displayName: "Values As Of Date",
				name: "values_as_of_date",
				type: "dateTime",
				default: "",
				description: "Werte Stand",
			},
			{
				displayName: "Guaranteed Pension",
				name: "guaranteed_pension",
				type: "number",
				default: 0,
				description: "Garantierte Rente (€)",
			},
			{
				displayName: "Expected Pension",
				name: "expected_pension",
				type: "number",
				default: 0,
				description: "Prognostizierte Rente (€)",
			},
			{
				displayName: "Guaranteed Capital",
				name: "guaranteed_capital",
				type: "number",
				default: 0,
				description: "Garantiertes Kapital (€)",
			},
			{
				displayName: "Expected Capital",
				name: "expected_capital",
				type: "number",
				default: 0,
				description: "Prognostiziertes Kapital (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "AV Riders",
				name: "av_riders",
				type: "multiOptions",
				options: [{ name: "BUZ", value: "buz" }, { name: "Beitragsbefreiung Bei BU", value: "premium_waiver_bu" }, { name: "Pflegeoption", value: "care_option" }, { name: "Unfall-Zusatz", value: "accident_rider" }],
				default: [],
				description: "Zusatzbausteine",
			},
			{
				displayName: "Buz Monthly Pension",
				name: "buz_monthly_pension",
				type: "number",
				default: 0,
				description: "BUZ-Monatsrente (€)",
			},
			{
				displayName: "Accident Rider Sum",
				name: "accident_rider_sum",
				type: "number",
				default: 0,
				description: "Unfall-Zusatz Summe (€)",
			},
			{
				displayName: "Survivor Protection",
				name: "survivor_protection",
				type: "multiOptions",
				options: [{ name: "Beitragsrückgewähr", value: "premium_refund" }, { name: "Hinterbliebenenrente", value: "survivor_pension" }, { name: "Rentengarantiezeit", value: "pension_guarantee_period" }, { name: "Todesfallkapital", value: "death_capital" }],
				default: [],
				description: "Todesfall-/Hinterbliebenenschutz",
			},
			{
				displayName: "Pension Guarantee Years",
				name: "pension_guarantee_years",
				type: "number",
				default: 0,
				description: "Rentengarantiezeit (Jahre)",
			},
			{
				displayName: "Death Benefit Amount",
				name: "death_benefit_amount",
				type: "number",
				default: 0,
				description: "Todesfallkapital (€)",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "asset",
		type: "other",
		paramName: "assetOtherFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Monthly Payment",
				name: "monthly_payment",
				type: "number",
				default: 0,
				description: "Monatliche Zahlung",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert",
			},
			{
				displayName: "Duration",
				name: "duration",
				type: "options",
				options: [{ name: "Kurzfristig", value: "short" }, { name: "Langfristig", value: "long" }, { name: "Mittelfristig", value: "middle" }],
				default: "middle",
				description: 'Laufzeit-Bucket. Wird bei typed Asset-Endpoints server-seitig aus dem Contract-Type abgeleitet — nur `/asset/other` akzeptiert einen Client-Wert.',
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "liability_insurance",
		paramName: "hedgeLiabilityInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Versicherungssumme (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Selbstbeteiligung (€)",
			},
			{
				displayName: "Family Status",
				name: "family_status",
				type: "options",
				options: [{ name: "Familie", value: "family" }, { name: "Paar", value: "couple" }, { name: "Single", value: "single" }],
				default: "family",
				description: "Familienstatus",
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Deliktunfähige Kinder", value: "incapable_children" }, { name: "Forderungsausfall", value: "default_failure" }, { name: "Gefälligkeitsschäden", value: "courtesy_damages" }, { name: "Gewässerschaden", value: "water_damage" }, { name: "Schlüsselverlust", value: "key_loss" }],
				default: [],
				description: "Eingeschlossene Bausteine",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "car_insurance",
		paramName: "hedgeCarInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "License Plate",
				name: "license_plate",
				type: "string",
				default: "",
				description: "Kennzeichen",
			},
			{
				displayName: "Hsn",
				name: "hsn",
				type: "string",
				default: "",
			},
			{
				displayName: "Tsn",
				name: "tsn",
				type: "string",
				default: "",
			},
			{
				displayName: "Initial Registration Date",
				name: "initial_registration_date",
				type: "dateTime",
				default: "",
				description: "Erstzulassung",
			},
			{
				displayName: "Coverage Scope",
				name: "coverage_scope",
				type: "options",
				options: [{ name: "Haftpflicht", value: "liability" }, { name: "Haftpflicht + Teilkasko", value: "liability_partial" }, { name: "Vollkasko", value: "full" }],
				default: "liability",
				description: "Deckungsart",
			},
			{
				displayName: "No Claims Class Liability",
				name: "no_claims_class_liability",
				type: "string",
				default: "",
				description: "SF-Klasse Haftpflicht",
			},
			{
				displayName: "No Claims Class Full",
				name: "no_claims_class_full",
				type: "string",
				default: "",
				description: "SF-Klasse Vollkasko",
			},
			{
				displayName: "Partial Deductible",
				name: "partial_deductible",
				type: "number",
				default: 0,
				description: "SB Teilkasko (€)",
			},
			{
				displayName: "Full Deductible",
				name: "full_deductible",
				type: "number",
				default: 0,
				description: "SB Vollkasko (€)",
			},
			{
				displayName: "Annual Mileage",
				name: "annual_mileage",
				type: "number",
				default: 0,
				description: "Jährliche Fahrleistung (km)",
			},
			{
				displayName: "Driver Group",
				name: "driver_group",
				type: "options",
				options: [{ name: "Familie", value: "family" }, { name: "Nur VN", value: "vn_only" }, { name: "Offen", value: "open" }, { name: "VN + Partner", value: "vn_partner" }],
				default: "family",
				description: "Nutzerkreis",
			},
			{
				displayName: "Add Ons",
				name: "add_ons",
				type: "multiOptions",
				options: [{ name: "Fahrerschutz", value: "driver_protection" }, { name: "GAP", value: "gap" }, { name: "Rabattschutz", value: "discount_protection" }, { name: "Schutzbrief", value: "roadside" }, { name: "Werkstattbindung", value: "workshop_binding" }],
				default: [],
				description: "Zusatzbausteine",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "household_contents_insurance",
		paramName: "hedgeHouseholdContentsInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Versicherungssumme (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Selbstbeteiligung (€)",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Wohnfläche (m²)",
			},
			{
				displayName: "Risk Street",
				name: "risk_street",
				type: "string",
				default: "",
				description: "Risikoort: Straße",
			},
			{
				displayName: "Risk Street Number",
				name: "risk_street_number",
				type: "string",
				default: "",
				description: "Risikoort: Hausnummer",
			},
			{
				displayName: "Risk Zipcode",
				name: "risk_zipcode",
				type: "string",
				default: "",
				description: "Risikoort: PLZ",
			},
			{
				displayName: "Risk City",
				name: "risk_city",
				type: "string",
				default: "",
				description: "Risikoort: Stadt",
			},
			{
				displayName: "Burglary Alarm",
				name: "burglary_alarm",
				type: "boolean",
				default: false,
				description: "Whether einbruchmeldeanlage vorhanden",
			},
			{
				displayName: "Elemental Coverage",
				name: "elemental_coverage",
				type: "boolean",
				default: false,
				description: "Whether elementarschäden eingeschlossen",
			},
			{
				displayName: "Glass Coverage",
				name: "glass_coverage",
				type: "boolean",
				default: false,
				description: "Whether glasbruch eingeschlossen",
			},
			{
				displayName: "Bicycle Coverage Sum",
				name: "bicycle_coverage_sum",
				type: "number",
				default: 0,
				description: "Fahrradklausel Summe (€)",
			},
			{
				displayName: "Valuables Sum",
				name: "valuables_sum",
				type: "number",
				default: 0,
				description: "Wertsachen-Summe (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "legal_protection_insurance",
		paramName: "hedgeLegalProtectionInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Deckungssumme (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Selbstbeteiligung (€)",
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Beruf", value: "job" }, { name: "Gewerbe", value: "business" }, { name: "Immobilien Vermietet", value: "rental_property" }, { name: "Privat", value: "private" }, { name: "Verkehr", value: "traffic" }, { name: "Wohnen-Eigentümer", value: "owner" }, { name: "Wohnen-Mieter", value: "tenant" }],
				default: [],
				description: "Eingeschlossene Bausteine",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "residential_building_insurance",
		paramName: "hedgeResidentialBuildingInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Versicherungssumme / Wert 1914 (€)",
			},
			{
				displayName: "Deductible",
				name: "deductible",
				type: "number",
				default: 0,
				description: "Selbstbeteiligung (€)",
			},
			{
				displayName: "Risk Street",
				name: "risk_street",
				type: "string",
				default: "",
				description: "Risikoort: Straße",
			},
			{
				displayName: "Risk Street Number",
				name: "risk_street_number",
				type: "string",
				default: "",
				description: "Risikoort: Hausnummer",
			},
			{
				displayName: "Risk Zipcode",
				name: "risk_zipcode",
				type: "string",
				default: "",
				description: "Risikoort: PLZ",
			},
			{
				displayName: "Risk City",
				name: "risk_city",
				type: "string",
				default: "",
				description: "Risikoort: Stadt",
			},
			{
				displayName: "Building Type",
				name: "building_type",
				type: "options",
				options: [{ name: "Doppelhaushälfte", value: "dhh" }, { name: "Einfamilienhaus", value: "efh" }, { name: "Mehrfamilienhaus", value: "mfh" }, { name: "Reihenhaus", value: "rh" }],
				default: "dhh",
				description: "Gebäudeart",
			},
			{
				displayName: "Construction Year",
				name: "construction_year",
				type: "number",
				default: 0,
				description: "Baujahr",
			},
			{
				displayName: "Living Area",
				name: "living_area",
				type: "number",
				default: 0,
				description: "Wohnfläche (m²)",
			},
			{
				displayName: "Construction Class",
				name: "construction_class",
				type: "options",
				options: [{ name: "Fertighaus", value: "prefab" }, { name: "Holz", value: "wood" }, { name: "Massiv", value: "solid" }],
				default: "prefab",
				description: "Bauartklasse",
			},
			{
				displayName: "Roof Type",
				name: "roof_type",
				type: "options",
				options: [{ name: "Hart", value: "hard" }, { name: "Weich", value: "soft" }],
				default: "hard",
				description: "Dacheindeckung",
			},
			{
				displayName: "Hazards",
				name: "hazards",
				type: "multiOptions",
				options: [{ name: "Elementar", value: "elemental" }, { name: "Feuer", value: "fire" }, { name: "Leitungswasser", value: "water" }, { name: "Sturm + Hagel", value: "storm_hail" }, { name: "Unbenannte Gefahren", value: "unnamed" }],
				default: [],
				description: "Eingeschlossene Gefahren",
			},
			{
				displayName: "Photovoltaic Coverage",
				name: "photovoltaic_coverage",
				type: "boolean",
				default: false,
				description: "Whether photovoltaik eingeschlossen",
			},
			{
				displayName: "Gross Negligence",
				name: "gross_negligence",
				type: "boolean",
				default: false,
				description: "Whether grobe Fahrlässigkeit eingeschlossen",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "accident_insurance",
		paramName: "hedgeAccidentInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Grundsumme Invalidität (€)",
			},
			{
				displayName: "Progression Rate",
				name: "progression_rate",
				type: "options",
				options: [{ name: "100 %", value: "100" }, { name: "1000 %", value: "1000" }, { name: "225 %", value: "225" }, { name: "350 %", value: "350" }, { name: "500 %", value: "500" }],
				default: "100",
				description: "Progression",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamik (%)",
			},
			{
				displayName: "Accident Pension From Invalidity",
				name: "accident_pension_from_invalidity",
				type: "number",
				default: 0,
				description: "Unfallrente ab Invalidität (%)",
			},
			{
				displayName: "Monthly Accident Pension",
				name: "monthly_accident_pension",
				type: "number",
				default: 0,
				description: "Monatliche Unfallrente (€)",
			},
			{
				displayName: "Hospital Daily Allowance",
				name: "hospital_daily_allowance",
				type: "number",
				default: 0,
				description: "Krankenhaustagegeld (€)",
			},
			{
				displayName: "Accident Death Benefit",
				name: "accident_death_benefit",
				type: "number",
				default: 0,
				description: "Todesfallsumme (€)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "term_life_insurance",
		paramName: "hedgeTermLifeInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Versicherungssumme (€)",
			},
			{
				displayName: "Sum Progression",
				name: "sum_progression",
				type: "options",
				options: [{ name: "Annuitätisch Fallend", value: "annuity_falling" }, { name: "Konstant", value: "constant" }, { name: "Linear Fallend", value: "linear_falling" }],
				default: "annuity_falling",
				description: "Summenverlauf",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamik (%)",
			},
			{
				displayName: "Subsequent Insurance Guarantee",
				name: "subsequent_insurance_guarantee",
				type: "boolean",
				default: false,
				description: "Whether nachversicherungsgarantie",
			},
			{
				displayName: "Smoker Status",
				name: "smoker_status",
				type: "options",
				options: [{ name: "Nichtraucher", value: "non_smoker" }, { name: "Raucher", value: "smoker" }],
				default: "non_smoker",
				description: "Raucher-Status bei Antrag",
			},
			{
				displayName: "Purpose",
				name: "purpose",
				type: "options",
				options: [{ name: "Familie", value: "family" }, { name: "Finanzierung", value: "financing" }, { name: "Geschäftspartner", value: "business_partner" }],
				default: "family",
				description: "Verwendungszweck",
			},
			{
				displayName: "Cross Insurance",
				name: "cross_insurance",
				type: "boolean",
				default: false,
				description: "Whether überkreuzversicherung",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "income_protection_insurance",
		paramName: "hedgeIncomeProtectionInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Insurance Sum",
				name: "insurance_sum",
				type: "number",
				default: 0,
				description: "Versicherte Monatsrente (€)",
			},
			{
				displayName: "Benefit Until Age",
				name: "benefit_until_age",
				type: "number",
				default: 0,
				description: "Leistungsdauer bis Alter",
			},
			{
				displayName: "Occupation At Application",
				name: "occupation_at_application",
				type: "string",
				default: "",
				description: "Beruf bei Antragstellung",
			},
			{
				displayName: "Contribution Dynamic",
				name: "contribution_dynamic",
				type: "number",
				default: 0,
				description: "Beitragsdynamik (%)",
			},
			{
				displayName: "Benefit Dynamic",
				name: "benefit_dynamic",
				type: "number",
				default: 0,
				description: "Leistungsdynamik (%)",
			},
			{
				displayName: "Risk Surcharges Exclusions",
				name: "risk_surcharges_exclusions",
				type: "string",
				default: "",
				description: "Risikozuschläge / Ausschlüsse",
			},
			{
				displayName: "Subsequent Insurance Guarantee",
				name: "subsequent_insurance_guarantee",
				type: "boolean",
				default: false,
				description: "Whether nachversicherungsgarantie",
			},
			{
				displayName: "BU Riders",
				name: "bu_riders",
				type: "multiOptions",
				options: [{ name: "AU-Klausel", value: "au_clause" }, { name: "Beitragsbefreiung", value: "premium_waiver" }, { name: "Pflegeoption", value: "care_option" }, { name: "Schwere Krankheiten", value: "dread_disease" }],
				default: [],
				description: "Eingeschlossene Zusatzbausteine",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "optional_health_services",
		paramName: "hedgeOptionalHealthServicesFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Accommodation",
				name: "accommodation",
				type: "options",
				options: [{ name: "Einbett", value: "single_bed" }, { name: "Zweibett", value: "two_bed" }],
				default: "single_bed",
				description: "Unterbringung",
			},
			{
				displayName: "Chief Physician Treatment",
				name: "chief_physician_treatment",
				type: "boolean",
				default: false,
				description: "Whether chefarztbehandlung",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "Mit", value: "with" }, { name: "Ohne", value: "without" }],
				default: "with",
				description: "Altersrückstellungen",
			},
			{
				displayName: "Waiting Period Expired",
				name: "waiting_period_expired",
				type: "boolean",
				default: false,
				description: "Whether wartezeit abgelaufen",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "deferred_health_insurance",
		paramName: "hedgeDeferredHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Anwartschaft Type",
				name: "anwartschaft_type",
				type: "options",
				options: [{ name: "Große Anwartschaft", value: "large" }, { name: "Kleine Anwartschaft", value: "small" }],
				default: "large",
				description: "Art der Anwartschaft",
			},
			{
				displayName: "Target Tariff",
				name: "target_tariff",
				type: "string",
				default: "",
				description: "Zieltarif (PKV/Zusatz)",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "dental_supplementary_insurance",
		paramName: "hedgeDentalSupplementaryInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Dental Replacement Reimbursement",
				name: "dental_replacement_reimbursement",
				type: "number",
				default: 0,
				description: "Erstattung Zahnersatz (%)",
			},
			{
				displayName: "Dental Treatment Reimbursement",
				name: "dental_treatment_reimbursement",
				type: "number",
				default: 0,
				description: "Erstattung Zahnbehandlung (%)",
			},
			{
				displayName: "Prophylaxis Reimbursement",
				name: "prophylaxis_reimbursement",
				type: "number",
				default: 0,
				description: "Erstattung Prophylaxe (%)",
			},
			{
				displayName: "Annual Max Staging",
				name: "annual_max_staging",
				type: "string",
				default: "",
				description: "Jahreshöchstsatz / Staffelung",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "Mit", value: "with" }, { name: "Ohne", value: "without" }],
				default: "with",
				description: "Altersrückstellungen",
			},
			{
				displayName: "Waiting Period Expired",
				name: "waiting_period_expired",
				type: "boolean",
				default: false,
				description: "Whether wartezeit abgelaufen",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "travel_health_insurance",
		paramName: "hedgeTravelHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Persons Travel",
				name: "insured_persons_travel",
				type: "options",
				options: [{ name: "Einzelperson", value: "single" }, { name: "Familie", value: "family" }, { name: "Paar", value: "couple" }],
				default: "single",
				description: "Versicherte Personen",
			},
			{
				displayName: "Max Travel Duration Days",
				name: "max_travel_duration_days",
				type: "number",
				default: 0,
				description: 'Max. Reisedauer (Tage).',
			},
			{
				displayName: "Repatriation Included",
				name: "repatriation_included",
				type: "boolean",
				default: false,
				description: "Whether rücktransport eingeschlossen",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "private_health_insurance",
		paramName: "hedgePrivateHealthInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Insured Status",
				name: "insured_status",
				type: "options",
				options: [{ name: "Angestellter Über JAEG", value: "employee_above_jaeg" }, { name: "Beamter", value: "civil_servant" }, { name: "Kind", value: "child" }, { name: "Selbstständig", value: "self_employed" }, { name: "Student", value: "student" }],
				default: "employee_above_jaeg",
				description: "Versicherten-Status",
			},
			{
				displayName: "Aid Rate",
				name: "aid_rate",
				type: "number",
				default: 0,
				description: "Beihilfesatz (für Beamte) (%)",
			},
			{
				displayName: "Annual Deductible",
				name: "annual_deductible",
				type: "number",
				default: 0,
				description: 'Selbstbeteiligung p.a. (€).',
			},
			{
				displayName: "Modules",
				name: "modules",
				type: "multiOptions",
				options: [{ name: "Ambulant", value: "outpatient" }, { name: "Krankentagegeld", value: "daily_allowance" }, { name: "Pflegetagegeld", value: "care_allowance" }, { name: "Stationär", value: "inpatient" }, { name: "Zahn", value: "dental" }],
				default: [],
				description: "Eingeschlossene Bausteine",
			},
			{
				displayName: "Inpatient Benefit",
				name: "inpatient_benefit",
				type: "options",
				options: [{ name: "Einbett + Chefarzt", value: "single_bed_chief" }, { name: "Mehrbett", value: "multi_bed" }, { name: "Zweibett", value: "two_bed" }],
				default: "single_bed_chief",
				description: "Stationär-Leistung",
			},
			{
				displayName: "Dental Benefit",
				name: "dental_benefit",
				type: "number",
				default: 0,
				description: "Zahnleistung (%)",
			},
			{
				displayName: "Contribution Relief Tariff",
				name: "contribution_relief_tariff",
				type: "boolean",
				default: false,
				description: "Whether beitragsentlastungstarif eingeschlossen",
			},
			{
				displayName: "Relief From Age",
				name: "relief_from_age",
				type: "number",
				default: 0,
				description: "Ab Alter Entlastung",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "nursing_care_insurance",
		paramName: "hedgeNursingCareInsuranceFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Insured Person",
				name: "insured_person",
				type: "string",
				default: "",
				description: "Versicherte Person",
			},
			{
				displayName: "Care Insurance Type",
				name: "care_insurance_type",
				type: "options",
				options: [{ name: "Pflegekosten", value: "costs" }, { name: "Pflegerente", value: "pension" }, { name: "Pflegetagegeld", value: "daily_allowance" }],
				default: "costs",
				description: "Art der Pflegeversicherung",
			},
			{
				displayName: "Care Benefit Pg2",
				name: "care_benefit_pg2",
				type: "number",
				default: 0,
				description: "Leistung PG 2 (€)",
			},
			{
				displayName: "Care Benefit Pg3",
				name: "care_benefit_pg3",
				type: "number",
				default: 0,
				description: "Leistung PG 3 (€)",
			},
			{
				displayName: "Care Benefit Pg4",
				name: "care_benefit_pg4",
				type: "number",
				default: 0,
				description: "Leistung PG 4 (€)",
			},
			{
				displayName: "Care Benefit Pg5",
				name: "care_benefit_pg5",
				type: "number",
				default: 0,
				description: "Leistung PG 5 (€)",
			},
			{
				displayName: "Dynamic Rate",
				name: "dynamic_rate",
				type: "number",
				default: 0,
				description: "Dynamik (%)",
			},
			{
				displayName: "Aging Reserves",
				name: "aging_reserves",
				type: "options",
				options: [{ name: "Mit", value: "with" }, { name: "Ohne", value: "without" }],
				default: "with",
				description: "Altersrückstellungen",
			},
			{
				displayName: "Premium Waiver On Benefit",
				name: "premium_waiver_on_benefit",
				type: "boolean",
				default: false,
				description: "Whether beitragsbefreiung im Leistungsfall",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
	{
		category: "hedge",
		type: "other",
		paramName: "hedgeOtherFields",
		fields: [
			{
				displayName: "Corporation",
				name: "corporation",
				type: "string",
				default: "",
				description: "Vertragspartner (Unternehmen)",
			},
			{
				displayName: "Notes",
				name: "notes",
				type: "string",
				default: "",
				description: "Notizen",
			},
			{
				displayName: "Value",
				name: "value",
				type: "number",
				default: 0,
				description: "Aktueller Wert in EUR",
			},
			{
				displayName: "Payment Cycle",
				name: "payment_cycle",
				type: "options",
				options: [{ name: "14-Tägig", value: "bi_weekly" }, { name: "Halbjährlich", value: "half_yearly" }, { name: "Jährlich", value: "yearly" }, { name: "Monatlich", value: "monthly" }, { name: "Quartalsweise", value: "quarterly" }, { name: "Wöchentlich", value: "weekly" }, { name: "Zweimonatlich", value: "bi_monthly" }],
				default: "monthly",
				description: "Zahlungsintervall des Beitrages",
			},
			{
				displayName: "Contract Number",
				name: "contract_number",
				type: "string",
				default: "",
				description: "Vertragsnummer",
			},
			{
				displayName: "Start Date",
				name: "start_date",
				type: "dateTime",
				default: "",
				description: "Beginn",
			},
			{
				displayName: "End Date",
				name: "end_date",
				type: "dateTime",
				default: "",
				description: "Enddatum",
			},
			{
				displayName: "Description",
				name: "description",
				type: "string",
				default: "",
				description: "Kurzbeschreibung zum Vertrag",
				displayOptions: { show: { "/operation": ["update"] } },
			},
		],
	},
];
